name: Periodic

on:
  schedule:
    - cron: 0 0 * * SUN

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        toolchain: [stable, beta, nightly]
        features: ["", "compress"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features "${{ matrix.features }}"
